### ISSUE TITLE
Reproduzir planilha do projeto `acordo-judicial-reparacao-vale` utilizando modelagem link table no spreadmart

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/spreadmart#17]
@fjuniorr Após fazer a leitura dos arquivos na modelagem `linktable`, o painel `qlikview` `projetos_vale.qvw` apresentou a existência de 

- `uo_cod` == -4
- `ano` == Null
- `uo_cod` == Null
- `chave_exec` == Null

**Comment by hslinhares** [comment]
Isso pode estar acontecendo porque existem `chave_projetos_vale` sem correspondência em outras chaves

![image](https://github.com/splor-mg/spreadmart/assets/43452663/c5c6e807-d4ed-47de-a30f-d24e67e0d3a7)

**Comment by hslinhares** [comment]
Além disso, como não tem `ano` na `chave_rec` e na `chave_loa`, se existir alguma dotação na `receita` ou `loa` que não existir na `execucao` ou `RP`, vai retornar `ano` == `Null`. Se possível `ano` deve ser inserido nessas chaves.

**Comment by fjuniorr** [comment]
@hslinhares para evitar erros de memória vamos manter na link table somente os dados de 2024.

**Comment by fjuniorr** [comment]
Depois de https://github.com/splor-mg/dpm-r/pull/4 não faz sentido fazer o mesmo exercício para a planilha da vale.
